name: Build
on:
  push:
    branches:
      - main
      - beta
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - name: darwin
            os: macos-11
            node: x64
            command: prebuildify
            args: --arch x64+arm64
          - name: win32-x86
            os: windows-latest
            node: x86
            command: prebuildify
          - name: win32-x64
            os: windows-latest
            node: x64
            command: prebuildify
          - name: linux-x64
            os: ubuntu-latest
            command: prebuildify-cross
            args: -i centos7-devtoolset7 -i alpine
          - name: linux-arm
            os: ubuntu-latest
            command: prebuildify-cross
            args: -i linux-arm64 -i linux-armv7 -i linux-armv6
          - name: android-arm
            os: ubuntu-latest
            command: prebuildify-cross
            args: -i android-arm64 -i android-armv7
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          architecture: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run ${{ matrix.command }} -- ${{ matrix.args }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: prebuilds/
          if-no-files-found: error
      - if: failure()
        run: ls -la
  release:
    needs: prebuild
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: prebuilds
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
